[versions]
java = "11"
kotlin = "1.9.10"
coroutines = "1.7.3"

android-gradle = "8.1.2"
android-min = "21"
android-compile = "33"
androidx-activity = "1.8.0"
androidx-compose-compiler = "1.5.3"
androidx-compose-runtime = "1.5.3"
androidx-lifecycle = "2.6.2"
androidx-fragment = "1.6.2"
androidx-recyclerview = "1.3.2"

khonshu = "0.18.0"

adapterdelegates = "4.3.2"

rxjava = "2.2.21"

publish = "0.25.3"
dokka = "1.9.10"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "android-gradle" }

khonshu-statemachine = { module = "com.freeletics.khonshu:state-machine", version.ref = "khonshu" }

adapterdelegates = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version.ref = "adapterdelegates" }

rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
